#!/usr/bin/env python3
"""Turns ui/index.html into src/ui_page.c, a C string in the executable.

The page is authored as plain HTML so it can be opened straight in a
browser while being worked on; this makes it part of the binary so the
shipped client stays one file. Run after editing the page:

    python3 tools/embed-page.py
"""
import pathlib

root = pathlib.Path(__file__).resolve().parent.parent
html = (root / "ui" / "index.html").read_text(encoding="utf-8")

out = ["/*\n  The interface page, generated from ui/index.html by\n"
       "  tools/embed-page.py. Do not edit this file; edit the HTML.\n*/\n",
       '#include "ui_page.h"\n\n',
       "const char ui_page_html[] =\n"]

for line in html.splitlines():
    esc = line.replace("\\", "\\\\").replace('"', '\\"')
    out.append(f'    "{esc}\\n"\n')

out.append("    ;\n")
(root / "src" / "ui_page.c").write_text("".join(out), encoding="utf-8")

(root / "src" / "ui_page.h").write_text(
    "/*\n  The interface page, generated from ui/index.html. See\n"
    "  tools/embed-page.py.\n*/\n"
    "#ifndef XERABORA_UI_PAGE_H\n#define XERABORA_UI_PAGE_H\n\n"
    "extern const char ui_page_html[];\n\n#endif\n", encoding="utf-8")

print(f"embedded {len(html)} bytes into src/ui_page.c")
