/* Default notification sounds, embedded. Generated by tools/make-sounds.py. */
#ifndef PS2RA_SOUNDS_DATA_H
#define PS2RA_SOUNDS_DATA_H

extern const unsigned char sound_connect_wav[];
extern const unsigned int sound_connect_wav_len;
extern const unsigned char sound_disconnect_wav[];
extern const unsigned int sound_disconnect_wav_len;
extern const unsigned char sound_achievement_wav[];
extern const unsigned int sound_achievement_wav_len;

#endif
