#!/usr/bin/env python3
"""Generate the client's notification sounds.

Writes client/sounds/*.wav (for listening and for people who want to
replace them) and client/src/sounds_data.c with the same bytes as C
arrays, so the executable carries its defaults.

Run from the repository root:  python3 tools/make-sounds.py
"""
import math
import os
import struct
import wave

RATE = 22050
ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
WAV_DIR = os.path.join(ROOT, 'client', 'sounds')
C_FILE = os.path.join(ROOT, 'client', 'src', 'sounds_data.c')


def tone(freq, seconds, volume=0.5, attack=0.01, release=0.08, harmonics=(1.0, 0.25, 0.08)):
    """A soft bell-like note: a few harmonics with an exponential tail."""
    n = int(RATE * seconds)
    out = []
    for i in range(n):
        t = i / RATE
        env = min(1.0, t / attack) if attack > 0 else 1.0
        env *= math.exp(-t / max(release, 1e-6)) if t > seconds - release * 4 else 1.0
        env *= math.exp(-2.2 * t / seconds)
        s = 0.0
        for k, amp in enumerate(harmonics, start=1):
            s += amp * math.sin(2 * math.pi * freq * k * t)
        out.append(volume * env * s / sum(harmonics))
    return out


def silence(seconds):
    return [0.0] * int(RATE * seconds)


def mix(*parts):
    return [v for p in parts for v in p]


def overlay(a, b, offset_seconds):
    off = int(RATE * offset_seconds)
    out = list(a) + [0.0] * max(0, off + len(b) - len(a))
    for i, v in enumerate(b):
        out[off + i] += v
    return out


C5, E5, G5, C6, E6, G6 = 523.25, 659.25, 783.99, 1046.5, 1318.5, 1568.0
E4, C4, A4 = 329.63, 261.63, 440.0

SOUNDS = {
    # Two rising notes: the console has found the PC.
    'connect': mix(tone(C5, 0.16), tone(G5, 0.28, volume=0.45)),
    # Two falling notes, quieter: the link is gone.
    'disconnect': mix(tone(E4, 0.18, volume=0.4), tone(C4, 0.32, volume=0.35)),
    # A fast arpeggio into a long bright bell.
    'achievement': overlay(
        mix(tone(C5, 0.09), tone(E5, 0.09), tone(G5, 0.09), tone(C6, 0.7, volume=0.55, release=0.25)),
        tone(E6, 0.5, volume=0.18, release=0.2), 0.3),
}


def to_pcm(samples):
    peak = max(1e-6, max(abs(v) for v in samples))
    scale = 0.9 / peak if peak > 0.9 else 1.0
    return b''.join(struct.pack('<h', int(max(-1.0, min(1.0, v * scale)) * 32767)) for v in samples)


def wav_bytes(pcm):
    import io
    buf = io.BytesIO()
    with wave.open(buf, 'wb') as w:
        w.setnchannels(1)
        w.setsampwidth(2)
        w.setframerate(RATE)
        w.writeframes(pcm)
    return buf.getvalue()


def main():
    os.makedirs(WAV_DIR, exist_ok=True)
    chunks = []
    for name, samples in SOUNDS.items():
        data = wav_bytes(to_pcm(samples))
        with open(os.path.join(WAV_DIR, name + '.wav'), 'wb') as f:
            f.write(data)
        rows = [', '.join('0x%02x' % b for b in data[i:i + 16]) for i in range(0, len(data), 16)]
        chunks.append('const unsigned char sound_%s_wav[] = {\n    %s\n};\nconst unsigned int sound_%s_wav_len = %d;\n'
                      % (name, ',\n    '.join(rows), name, len(data)))
        print('%-12s %6d bytes, %.2f s' % (name, len(data), len(samples) / RATE))
    with open(C_FILE, 'w', newline='\n') as f:
        f.write('/* Generated by tools/make-sounds.py. Do not edit. */\n\n')
        f.write('#include "sounds_data.h"\n\n')
        f.write('\n'.join(chunks))


if __name__ == '__main__':
    main()
